### PR TITLE
Update index.liquid

### PR DESCRIPTION
**Pull request by miguelhasse**
Fixed infinite scroll pagination URL

### CODE REVIEW

**Comment by Woland2k** [comment]
Can you make sure to sign Virto Commerce Contributor License Agreement so we can accept this pull request? http://virtocommerce.com/contribute-agreement

**Comment by miguelhasse** [comment]
Hi Sasha, it's done!


Hope do be of help... keep up the excellent work.

Regards,
Miguel Hasse

________________________________

**Comment by Woland2k** [comment]
Thanks Miguel,
you are now added to contributor group.

**Comment by asvishnyakov** [comment]
Tested & accepted. @miguelhasse Thank you!

**Pull request merged**
